# Generated by Django 6.0.3 on 2026-03-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('lop', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lớp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('so_dt', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('diem_tb', models.FloatField(blank=True, null=True, verbose_name='Điểm TB')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
